### ISSUE TITLE
Language Bugs

### ISSUE THREAD

**Issue by catatonicChimp** [supergeorg/Grocy-SwiftUI#12]
Hey, 

Georg, loving it so far, 
Just to note found the following missing translations so far..
In the Master data Tab:
Standort -> Location
Kategorie -> Category 
And Inside a product from the Master data Tab, going into Edit Product,
Parent produkt -> Parent Product

**Comment by supergeorg** [comment]
It all seems correct for me, please provide device info (is it iPhone or iPad), your device and app language setting as well as screenshots of the problem.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-26 at 19 22 44](https://user-images.githubusercontent.com/24377292/119704343-d3379700-be57-11eb-9824-2939fc17e452.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-26 at 19 22 37](https://user-images.githubusercontent.com/24377292/119704351-d599f100-be57-11eb-9f14-673241f3d949.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-26 at 19 22 30](https://user-images.githubusercontent.com/24377292/119704352-d6328780-be57-11eb-9654-f40433b71f39.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-26 at 19 22 15](https://user-images.githubusercontent.com/24377292/119704354-d6cb1e00-be57-11eb-8ac8-1a90541293c8.png)

**Comment by catatonicChimp** [comment]
Hi

Iphone 12pro
Language set to english in the app
iphone is english(new Zealand)

![IMG_1068](https://user-images.githubusercontent.com/1394392/119812050-d6a44e80-bf3b-11eb-952b-6f0035f038a0.PNG)
![IMG_1067](https://user-images.githubusercontent.com/1394392/119812058-d906a880-bf3b-11eb-8c1d-6d42963f75ca.PNG)

**Comment by supergeorg** [comment]
Oh, I have overlooked this part. It was really quite old code, I am not sure why it was still there 🤷 
It should be fixed now and will be part of the next update.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-27 at 19 16 29](https://user-images.githubusercontent.com/24377292/119869813-f417ef00-bf20-11eb-8958-de4670370e9c.png)
Please feel free to report other language problems.
