### ISSUE TITLE
Always getting API-Error after latest iOS-APP Update

### ISSUE THREAD

**Issue by FelixM01** [supergeorg/Grocy-SwiftUI#128]
I updated the App today, since then I am getting API-Errors as soon as I open the App.

Log attached
[Grocy-SwiftUI_LOG.log](https://github.com/supergeorg/Grocy-SwiftUI/files/9595024/Grocy-SwiftUI_LOG.log)

Greets
Felix

**Comment by supergeorg** [comment]
This seems to be related to move on open not being available on Grocy Server versions older than 3.3.1.
If it is possible, upgrade your server. I will also try to find a fix for it, since I thought I implemented safeguards preventing this.

**Comment by FelixM01** [comment]
Thank you for your responce. 

I finally found the time to look into it, and found a mistake at my installation. 
Finally got it fixed, and now everythink works fine again :)

Greets
Felix
