### ISSUE TITLE
No Decimal Button on Number Entry Fields

### ISSUE THREAD

**Issue by maniacaris** [supergeorg/Grocy-SwiftUI#13]
When you're on the purchase/transfer/consume screen, there is no option for a decimal on the keypad for number entry fields. This prevents the entry of non-whole number values, which is particularly problematic for price entry.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/30615033/119885278-3c221c00-bef7-11eb-9a1a-477d9e13cee5.png">

**Comment by supergeorg** [comment]
The keyboard entry is not good, but it should work for now. And you can press return now.
I will revisit this issue when SwiftUI 3 is available.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-28 at 19 04 11](https://user-images.githubusercontent.com/24377292/120018532-97333c00-bfe7-11eb-87b0-ecb838282c1f.png)

**Comment by maniacaris** [comment]
Thanks!
