### ISSUE TITLE
CZE localisation

### ISSUE THREAD

**Issue by zemanl79** [supergeorg/Grocy-SwiftUI#130]
Hello Georg,
I would like to have app also in CZE language. I know, minor to translate. However, if there would be interest from Your side, I can translate by myself.
Rgds

**Comment by supergeorg** [comment]
Ok, I added some initial translation to the project.
For further translation, please refer to the [translation guide](https://github.com/supergeorg/Grocy-SwiftUI/blob/main/TRANSLATION.md) and get added on Transifex.

**Comment by zemanl79** [comment]
Can you approve my Transiflex requests?

**Comment by supergeorg** [comment]
Should be done now

**Comment by zemanl79** [comment]
Translated :)

**Comment by supergeorg** [comment]
ETA of the update is this Friday

**Comment by supergeorg** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-10-28 at 17 23 52](https://user-images.githubusercontent.com/24377292/198675190-ad2d839e-4996-49b2-b6ca-a5f560c6d55e.png)
It is added. I will publish the update soon.
