### ISSUE TITLE
No keyboard with dropdown menu of the 'Product' selection.

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#132]
If the 'Product' dropdown is used (accessible after, for example, scanning a new barcode, or in the Purchase/Consume/Transfer screens) I currently have to manually scroll to select a product. With over 300 products, this is currently quite cumbersome.

It would help if the keyboard would pop up and I could simply type the product name, which would filter the shown items.

(If I'm not mistaken, this used to be an existing feature, correct?)

**Comment by supergeorg** [comment]
On iOS, there is a search bar in the product picker. You have to click it and search for the product.
On macOS, just type the name you want to find on your keyboard, it will jump there.

**Comment by Hoffelhas** [comment]
I tried to look for it, but it doesn't seem to be there:

![image](https://user-images.githubusercontent.com/19412013/208311137-df619744-140a-4701-aa70-afc1352b986c.png.

If I press anything on this list it doesn't activate the keyboard.

**Comment by supergeorg** [comment]
Ok, it seems you are still on iOS 16.0.
The .navigationlink picker style was only available after the release of iOS 16.1, so I matched to that version.

It should be fixed now, but the better way to fix it should be updating your iOS (security and bug fixes).

**Comment by Hoffelhas** [comment]
Ah noted, will update. Thanks a lot for looking in to this!
