### ISSUE TITLE
UPC-A (12-digit) Barcode Support

### ISSUE THREAD

**Issue by dsizemore** [supergeorg/Grocy-SwiftUI#137]
Hi Georg,

When using the barcode scanner I noticed that none of our existing products (added with an [Android device](https://github.com/patzly/grocy-android)) were being recognized. In doing a bit of digging, it appears that the Android devices are reading the 12-digit barcodes as UPC-A, whereas the iPhone is converting them to EAN-13 by prepending a leading 0 to make it 13-digits. I noticed that the [AVMetadataObject.ObjectType](https://developer.apple.com/documentation/avfoundation/avmetadataobject/objecttype) framework/library/module (I'm not a Swift developer) you're using doesn't seem to explicitly support UPC-A. 

The [Apple Developer Tech Notes](https://developer.apple.com/library/archive/technotes/tn2325/_index.html#//apple_ref/doc/uid/DTS40013824-CH1-IS_UPC_A_SUPPORTED) say that UPC-A is supported because they are a subset of EAN-13. However, in practice, there is a conflict because the Apple devices are adding a leading zero to the 12-digit barcodes and Grocy cannot match the two. 

[This project](https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/176) (which appears to be using Nativescript rather than Swift) has a similar issue discussing the challenges. 

**Request**: Would it be possible to add an option to prevent 12-digit UPC-A barcodes from being automatically converted to EAN-13 by prepending the leading 0? This [Stackoverflow post](https://stackoverflow.com/questions/22767584/ios7-barcode-scanner-api-adds-a-zero-to-upca-barcode-format) mentioned in the above issue seems to offer a solution. You may need to pair it with an option checkbox which allows a user to enable/disable this behavior. 

Thank you for an excellent application!

**Comment by supergeorg** [comment]
Well, this seemed rather simple. I just check if the detected code is EAN-13 and remove the leading zero then.
Hope this doesn't break anything, although it should be not very likely.

**Comment by dsizemore** [comment]
That did fix it for our instance of Grocy. Thank you very much, Georg! 

If others have an instance of Grocy where UPC-A barcodes have been normalized to EAN-13 this fix could cause them problems, but a simple preferences toggle to enable/disable this behavior could solve for that if it crops up in the future. I appreciate your work on this!
