### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by mike9449** [supergeorg/Grocy-SwiftUI#140]
Hi, I want to help you to translate your app in Italian. How can I do that?

**Comment by supergeorg** [comment]
I will add the language to the project and to transifex when I find time for it. 
Then it just needs to be edited there.

**Comment by supergeorg** [comment]
Seems like Italian is added to Transifex.
My tool did its magic, now you have to register there and translate the strings.
It it is complete, I will build the app with the language integrated.
More information is found [here](https://github.com/supergeorg/Grocy-SwiftUI/blob/main/TRANSLATION.md).

**Comment by mike9449** [comment]
Ok thanks. I’ve translated all the strings.ThanksIl giorno 31 gen 2023, alle ore 23:15, Georg Meißner ***@***.***> ha scritto:﻿
Seems like Italian is added to Transifex.
My tool did its magic, now you have to register there and translate the strings.
It it is complete, I will build the app with the language integrated.
More information is found here.
