### ISSUE TITLE
Bug: master data due days of -1 results in due date of yesterday instead of never when scanning.

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#157]
Setting the 'default due days' of an item to '-1' in the master data of a product is intended to signify that the item will never be overdue. However, after scanning the product the due date is instead automatically put on 'yesterday', instead of triggering the never overdue toggle.

Important note: this only happens if you scan a purchase, not if you manually add a purchase.

**Comment by supergeorg** [comment]
The form missed handling for the never overdue value.
Should be fixed with the next update.
