### ISSUE TITLE
Add on apps (Pantry Party and Grocy Mobile (IOS app)) both fail with same error when attempting to add product to database when using bar code scanning.

### ISSUE THREAD

**Issue by kingswindsor** [supergeorg/Grocy-SwiftUI#164]
See [https://github.com/grocy/grocy/issues/2240](https://github.com/grocy/grocy/issues/2240)

There appears to be an incompatibility between Grocy Mobile (Grocy-SwiftUI) and Grocy v3.3.2 and likely also later releases with the removal of the qu_factor_purchase_to_stock field.

**Comment by berrnd** [comment]
> There appears to be an incompatibility between Pantry Party and Grocy v3.3.2 [...] with the removal of the qu_factor_purchase_to_stock field

Just to clarify that also here:
v3.3.2 **has not (!)** removed this field, so this can't be the problem when running the current Grocy release v3.3.2.

@kingswindsor is most likely running the current development version (see https://github.com/grocy/grocy/issues/2240#issuecomment-1556293526) and also uses an unsupported PHP runtime version, so naturally everything can go wrong without real surprise I guess.

**Comment by supergeorg** [comment]
Yeah, this is definitely an incompatibility. The App sends the field _qu_factor_purchase_to_stock_, but it is not in the database (anymore).
For this, a compatibility check is integrated in the App and warns the user if an incompatible version is used.
Until the next big update (Grocy 4.x ?) is released, the App will not be updated to reflect this behavior, since tracking non-release versions is too much a hassle.

**Comment by kingswindsor** [comment]
Thanks @supergeorg Yes, waiting for the next main release is a good idea rather than chasing development releases.  Just an observation though on the compatibility checker in your App - following on from my conversation with @berrnd referred to above, I've been checking out the Grocy versions to to find the one that works with your app.  

- v3.3.2 release branch works with your app.  Specifically it doesn't have the qu_factor_purchase_to_stock incompatibily.
- v3.3.2 master branch (default) doesn't work and throws the qu_factor_purchase_to_stock error when trying to add a new product.

I've attached screenshots from your app with both branches, and both have the green tick for compatibility.  @berrnd is using the master branch for development and this seems to have introduced incompatibility with the deletion of the qu_factor_purchase_to_stock field.  Maybe the compatibility checker needs to check for the v3.3.2 release branch and not just v3.3.2 (assuming that is what it does)?  

In the pics below, the instance with v3.3.2 master is the one with PHP v 8.2.6 and v3.3.2 release has PHP 8.0.28.  (By the way, PHP 8.2.6 seems to work fine despite Grocy only officially supporting PHP 8.0 (but v3.3.2 master branch requires PHP8.1.0 to run Apache2)).
![InkedIMG_1588](https://github.com/supergeorg/Grocy-SwiftUI/assets/7615805/b203bfdc-c173-4b4e-86dc-c2dec1a584f5)
![InkedIMG_1590](https://github.com/supergeorg/Grocy-SwiftUI/assets/7615805/f6411c64-e88c-4be2-ba0a-970da0f91759)

**Comment by berrnd** [comment]
> Ok, this seems strange.

Trying to shed some light into the mysterious darkness:

When [`MODE`](https://github.com/grocy/grocy/blob/8c033ff6c8ebb983d6f301011cc2933d7d87e7bf/config-dist.php#LL16-L19) is `production` (default), `demo` or `dev`, the version information is just taken from [`version.json`](https://github.com/grocy/grocy/blob/master/version.json).

When `MODE` is `prerelease`, the version is `pre-release-<head commit hash>` and the release date is the timestamp of that same commit ([code ref](https://github.com/grocy/grocy/blob/8c033ff6c8ebb983d6f301011cc2933d7d87e7bf/services/ApplicationService.php#L55-L64) for all that).

`MODE` is set to `demo` for the [current release / stable demo](https://demo.grocy.info) and to `prerelease` for the [pre-release demo](https://demo-prerelease.grocy.info), I can't say and have no control over how that is set on any personal instance (it defaults to `production`).

The `master` branch in "production" should only be used by those who really know what they do and by those who can handle everything needed for that (especially database migrations, [README ref](https://github.com/grocy/grocy#database-migrations)). I personally even use always the latest release for my personal Grocy instance.
