### ISSUE TITLE
In transifex (Translation of Chinese (China) (zh_CN) that has been basically completed)

### ISSUE THREAD

**Issue by 2421715443** [supergeorg/Grocy-SwiftUI#166]
@supergeorg please handle
Please review and merge this translation into the main version, and I will review the translation effect and improve it in the future.
Note: This paragraph was translated by a translation software. Please understand the tone issue

**Comment by supergeorg** [comment]
I will look into this today or tomorrow. Please be patient.

**Comment by supergeorg** [comment]
OK, an update is review and should be available soon.
Please test it and check if it is to your satisfaction. Since many internal features are used, things like date and relative times seem to work fine and need no adaptation.

**Comment by 2421715443** [comment]
OK, I will check the possible problems in my translation and improve it after the application is launched, because part of the translation of this version lacks context.

**Comment by 2421715443** [comment]
in version 2.9.1
The Chinese language option does not appear in the language list.
Please check the reason.

**Comment by supergeorg** [comment]
Since it is experimental, it is hidden in DEV Mode. 
In settings menu -> App settings enable it and you can select Chinese.
