### ISSUE TITLE
Consume fails in iOS/MacOS App: Fail Message but correct calculations

### ISSUE THREAD

**Issue by SvenJachalke** [supergeorg/Grocy-SwiftUI#191]
Hi to all,

I created a new issue, although its very similar to #185:
Each time I consume a product (independent of quick-consume or regular consume) I got the red pop-up error "consume failed". But the number of products decreased by the previously consumed amount ... that's working as expected, but the message is misleading.

The AppLog provides the following:

09.12.2023, 20:07:42: Consume failed: decodingError(error: Grocy_Mobile.APIError.errorString(description: "Shopping list does not exist"))

For me a missing shopping list is not related to consumption?

About my Grocy Installation:
- Grocy 4.0.3 is running in a docker on my Synology NAS 
- Grocy iOS App 2.10.3.

I hope you can help me.
Thanks in advance!

_Originally posted by @SvenJachalke in https://github.com/supergeorg/Grocy-SwiftUI/issues/185#issuecomment-1848622336_

**Comment by supergeorg** [comment]
Well, this error seems to be thrown by the Grocy Server itself (somewhere in /services/StockService.php)

I think the main culprit for this is a missing/wrong setting in the App. The function "AddMissingProductsToShoppingList" can trigger this error, and is the most likely candidate for that.
Please check if Settings -> Shopping list settings -> Automatically add ... is enabled and a shopping list is selected.

**Comment by SvenJachalke** [comment]
Awesome!
You were absolutely right ... I guess, I deleted all shopping lists, which then cased this error. But really unintuitive.
But thanks a lot for the solution!
