### ISSUE TITLE
Decoding errors

### ISSUE THREAD

**Issue by mam** [supergeorg/Grocy-SwiftUI#22]
Hi,
The recent update has so far given me a couple of errors: 
1) Could not access the 'Stock overview' page. Following error was thrown in the log: 
`18:33:31.501 ERROR GrocyViewModel.requestData():382 - Data request failed for SystemConfig. Message: decodingError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "CALENDAR_FIRST_DAY_OF_WEEK", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))) `

I did a workaround by setting that particular config parameter on server from '1' to ''

2) I tried to consume a product from stock, but had no effect and this error was logged:
`18:40:52.798 ERROR GrocyViewModel.getStockProductEntries():735 - Get stock product details failed. decodingError(error: Swift.DecodingError.valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "purchased_date", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil)))`

I also am not able to do inventory on a product; nothing happens but didn't find an error in log.

**Comment by supergeorg** [comment]
The first one was caused by settings which are not set in demo or my server, so I missed the correct data type.
The second one seems to be caused by a migration of an old version, since a purchase date should be added to every product now. I made it optional nonetheless.

Please report if you find more errors.
