### ISSUE TITLE
Error: "Expected to decode Int but found a string/data instead."

### ISSUE THREAD

**Issue by matematrix** [supergeorg/Grocy-SwiftUI#23]
Hi,

I am new to the app but found it awesome from the screenshots. Sadly I was only able to log in throught the API credentials, but every other area of the app besides the settings show: "No connection to the server". But there must be a connection as the log shows that the login was successfull and I can view the user information.

However I always receive the following error in the logs:

`21:08:14.379 ERROR GrocyViewModel.getEntity():179 - Get entity products failed. decodingError(error: Swift.DecodingError.typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 130", intValue: 130), CodingKeys(stringValue: "cumulate_min_stock_amount_of_sub_products", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil)))`

as well as 

`21:08:14.383 ERROR GrocyViewModel.requestData():257 - Data request failed for products. Message: decodingError(error: Swift.DecodingError.typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 130", intValue: 130), CodingKeys(stringValue: "cumulate_min_stock_amount_of_sub_products", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil)))`

If any further information is needed, I will gladly add it to this issue :)

**Comment by llewy** [comment]
Can you open the grocy.db? 

Perform this one:

Update products set cumulate_min_stock_amount_of_sub_products = 0 where cumulate_min_stock_amount_of_sub_products = ''

**Comment by supergeorg** [comment]
It should be fixed in the new 1.1.2 version. If not, please tell me.
