### ISSUE TITLE
Indentation off

### ISSUE THREAD

**Issue by llewy** [supergeorg/Grocy-SwiftUI#24]
When I compare this screenshot to the one in the screenshots folder, I noticed there must be something wrong but can’t figure it out.

![EBB8B253-5096-4AD4-89FA-7B384BD93F22](https://user-images.githubusercontent.com/525767/126889794-bb55e276-c931-4453-b0d3-bce7fd706d9e.png)

**Comment by supergeorg** [comment]
This may be due to some changes in the layout. The screenshots are rather old and do not represent the current layout to a pixel. It is more like a general direction. But I will check if the indentations are correct and needed.
