### ISSUE TITLE
Wrong due date when adding a purchased item

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#41]
When scanning a product, the standard due date is set to 'today' instead of the one specified in the master data.

Ideally, I want to due date from the master data to be filled in; this seems to work fine for the amount, store, and location.

**Comment by supergeorg** [comment]
Thank you for noticing this, it was just not implemented. It is now and will release with the next update.

**Comment by Hoffelhas** [comment]
Awesome, thanks for the update!
