### ISSUE TITLE
Product pictures not uploadable

### ISSUE THREAD

**Issue by andreheuer** [supergeorg/Grocy-SwiftUI#42]
I want to make pictures of my products stored in grocy using my phone camera (i.e. not uploading an image from the gallery, but shooting a new photo). After clicking on "Take photo", the camera open and I can take picture. However, I cannot push any of the buttons neither on the lower left (repeat) nor on the lower right corner (use photo). I have to close the app and restart. Is this maybe related to #15?

```
Grocy Version: 3.1.3
iPhone X
iOS 15.1
Grocy mobile 1.2.2
```

**Comment by supergeorg** [comment]
Oops, this was a really small copy-paste error which slipped in.
It is fixed now and will be released in the next version.

**Comment by 404alex** [comment]
I have the same issue, cannot hit retake or use photo. Latest app, iOS 15.4.1. Also, the picture that added in Web seems not loading in the app, only loading icon. 

Thanks!
