### ISSUE TITLE
Support Grocy Code for scanning #enhancement

### ISSUE THREAD

**Issue by andreheuer** [supergeorg/Grocy-SwiftUI#44]
In one of the past version of Grocy, the Grocy Code has been introduced (see https://github.com/grocy/grocy/blob/master/docs/grocycode.md). This allows to easily identify products, batteries and chores with e.g. printed labels. Printing these labels is already supported with Grocy.

So I would like to propose the enhancement to be also able to scan grocy code. Decoding the code is completely offline, so there is no need to send the code to grocy first to decode the string.

**Comment by supergeorg** [comment]
This looks doable. I will look into it when I have some time for it.

For now, only products and stock entries will be supported. But this will be enough, I guess.

**Comment by supergeorg** [comment]
Should be supported now. Please check if it works in the upcoming version.
