### ISSUE TITLE
CurrencyFormatter.swift missing

### ISSUE THREAD

**Issue by andreheuer** [supergeorg/Grocy-SwiftUI#45]
I would like to work on solution for #44 and therefore cloned the repo. However, the compilation in Xcode fails due a missing file "CurrencyFormatter.swift".
After searching in the repo, I cannot find the file at all. Maybe it was missed out?

**Comment by supergeorg** [comment]
It is not needed. Don't know how it is still in the project.

A quick hotfix would be to delete the reference in proj.pbxproj

I will also fix it soon.

**Comment by supergeorg** [comment]
Please tell if other files show as missing.
