### ISSUE TITLE
Wrong conversion quantity during purchase

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#49]
I have an item that has a purchase quantity 'pack', with a conversion to a certain amount of 'grams' for my stock.

After scanning the item in 'purchase', I am able to add it as one pack, however the resulting stock amount is only 1 gram.

Ideally, I would like that the master data conversion settings are used to specify the stock amount.

**Comment by supergeorg** [comment]
Well, it was not implemented, but should be now.

**Comment by Hoffelhas** [comment]
Awesome, thanks a lot for the quick implementation!
