### ISSUE TITLE
No 'quick' consumption usage possible

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#50]
When using 'consume', the default value always equals 1 stock unit. Would it be possible to include, or make the quick use amount default (as specified in the master data)?

**Comment by supergeorg** [comment]
It would be possible to add this as an option.
The default is (like the Web interface) 1.
I will consider it in an upcoming options menu.

**Comment by Hoffelhas** [comment]
That would be very helpful! Thanks for the quick feedback!
