### ISSUE TITLE
Crash when scanning API Keys Barcode on iOS 15.1,  app v2.0.1, Grocy v3.1.3

### ISSUE THREAD

**Issue by MaoZ1993** [supergeorg/Grocy-SwiftUI#52]
First-time use, when I selected Own server, and then scan QR code from Hass grocy addon, the API key was recognised and URL is incomplete, starting with /api/xxxxx, when I tried to correct the URL, the APP crash and never allow me to enter "own server" page again.

Log shows incorrect URL, I'm not sure how to generate correct URL. And due to the crash I have no chance to make correction.

I'm using NGINX Home Assistant SSL proxy add-on to provide internal HTTP and external https access. 

[Grocy-SwiftUI_LOG.log](https://github.com/supergeorg/Grocy-SwiftUI/files/7750802/Grocy-SwiftUI_LOG.log)

**Comment by supergeorg** [comment]
It looks like that your URL is missing the `http://` bit. ([StackOverflow](https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description))
Please check if it is valid (it should be somewhere in the server config).
I also removed a force unwrap, hope this fixes the crash.

**Comment by MaoZ1993** [comment]
> It looks like that your URL is missing the `http://` bit. ([StackOverflow](https://stackoverflow.com/questions/26647423/nsurlerrordomain-error-code-1002-description)) Please check if it is valid (it should be somewhere in the server config). I also removed a force unwrap, hope this fixes the crash.

The fix is Great! Crash issue solved in v2.0.2. Thanks @supergeorg
