### ISSUE TITLE
Barcode unit conversions not functioning on purchases on iOS

### ISSUE THREAD

**Issue by Will711990** [supergeorg/Grocy-SwiftUI#53]
Hi, I allow myself to copy a bad placed subject from an other page :

When scanning purchases into grocy from the iOS app, barcode unit conversions don't seem to be functioning correctly. They work fine when scanned into the web app.
For example i have eggs:
Quantity unit stock: piece
Default quantity unit purchase: piece
Factor purchase to stock quantity unit: 1
----- This means 1 Pack purchased will be converted into 1 Piece in stock

Barcode: 4099100278804
Amount: 12
Quantity unit: piece

On the web app I go to purchase and scan 4099100278804, it will enter 12 pieces into eggs.
On iOS I go to quick scan, tap purchase tab at top, scan barcode 4099100278804, it will enter 1 piece into eggs.

**Comment by skipper22hassio** [comment]
Same as #40?

**Comment by Will711990** [comment]
Yes...
