### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by Will711990** [supergeorg/Grocy-SwiftUI#54]
Hi, I'm motivated to translate the application in French, but I absolutly not how to do this... neither how to request this properly on github.
I count on your kindness, to lead me on the right page :)

Thank you

**Comment by chpego** [comment]
Hi @Will711990 , i think we can fork the project, and add files on the folder Shared > fr.lproj > Localizable.strings

**Comment by Will711990** [comment]
Thanx !
I'm now logged on transifex, and French is a language asked. But it doesn't appear in "Proposed Languages" when I "Join Team"

**Comment by chpego** [comment]
I made the request too, I think we have to wait for a validation, maybe @supergeorg  has an idea?

**Comment by supergeorg** [comment]
Sorry, I didn't look into Transifex for some time. You should be confirmed now.
Bonne chance!

**Comment by supergeorg** [comment]
Ok, it is merged and the update is uploaded.
![screenshot_grocy_french](https://user-images.githubusercontent.com/24377292/149565132-2719a15f-c5a4-41e4-8d57-2ff441a17532.jpeg)
Thank you for your contribution!

**Comment by Will711990** [comment]
Hi ! 
I updated some translations which were inconstents when I used the app ! (No needs to push an app update for only this, but the next time)
:)
