### ISSUE TITLE
Shopping list items that aren't products render as "name error"

### ISSUE THREAD

**Issue by dgrnbrg** [supergeorg/Grocy-SwiftUI#58]
Hello, I often need to buy things as a one-off. In the web UI, these items are just notes and show up instead of the product name. I'd like it if this UI supported the same thing, so that the notes would show up in my shopping list.

**Comment by supergeorg** [comment]
I wasn't aware this was a feature. It should be working now (with the next update).
I also fixed some bugs with the implementation and display of shopping lists actions.
