### ISSUE TITLE
Shopping List & Stock overview

### ISSUE THREAD

**Issue by Will711990** [supergeorg/Grocy-SwiftUI#59]
Hi,

about "Below min. stock amount", only products already in stock are listed.
It would be easier if all products categorised "Below min. stock amount" were listed (like web page)

For example : 
On webpage : I have 15 products  "Below min. stock amount"
On iOS/MacOS/iPadOS : I have 4 products  "Below min. stock amount"

That a problem to add products in a shopping list !

Does it possible to add this ?

Thank you :)

**Comment by supergeorg** [comment]
I have added the functionality and hope that this works for you.
It will release with the next update.
