### ISSUE TITLE
Build failure: missing files

### ISSUE THREAD

**Issue by jpeyer** [supergeorg/Grocy-SwiftUI#7]
Thanks you for your hard work on this so far! Grocy is great, but a nice SwiftUI-based client will make it even better. 😃

I pulled down the code and tried to build, but it seems like a few files referenced in the Xcode project file aren't in the git repo. Here's the Xcode error I'm seeing:
```
error: Build input files cannot be found: 
'Grocy-SwiftUI/Shared/Model/OpenFoodFacts/OpenFoodFactsViewModel.swift',
'Grocy-SwiftUI/Shared/Views/Additional/UserEntityView.swift',
'Grocy-SwiftUI/Shared/Views/Settings/LogView.swift',
'Grocy-SwiftUI/iOS/ActivitiesView.swift',
'Grocy-SwiftUI/Shared/Views/Additional/OpenFoodFactsView.swift',
'Grocy-SwiftUI/Shared/Model/OpenFoodFacts/OpenFoodFactsModel.swift',
'Grocy-SwiftUI/Shared/Views/Additional/OpenFoodFactsScannerView.swift'
(in target 'Grocy-SwiftUI (iOS)' from project 'Grocy-SwiftUI')
```
I indeed do not see those files in the repo, and they appear to be used by your code and aren't just old references.

**Comment by supergeorg** [comment]
Oh, sorry, the files are not used yet, so I haven't pushed them.

I have done so now with commit `d23c51fc19c2a8167169cdaa97b6a73ce2ec5c44`, it should work now. (The features are hidden behind a dev mode toggle for now).
If you have any other issues, feel free to ask.

**Comment by jpeyer** [comment]
That did the trick, it now compiles without issue. Thanks!
