### ISSUE TITLE
Wrong display quantity

### ISSUE THREAD

**Issue by Will711990** [supergeorg/Grocy-SwiftUI#73]
Hi,

I've got a problem on quantity display:
<img width="1440" alt="Capture d’écran 2022-01-22 à 12 18 01" src="https://user-images.githubusercontent.com/25400986/150636493-2c802ebb-0557-4302-8bf0-2cc4201832eb.png">

This problem comes only with French language. I look up the translation, but I don't see any difference with similar translations.

Thank you !! :)

**Comment by supergeorg** [comment]
It is a typo in there, instead of ll it is II. 
Don't know what caused it, but it will need to be fixed in Transifex.

**Comment by supergeorg** [comment]
Ok, PR #88 should have fixed that.
It is tricky, since Transifex doesn't recognize it as a dynamic value.
