### ISSUE TITLE
Ability to specify total price of purchase

### ISSUE THREAD

**Issue by Hoffelhas** [supergeorg/Grocy-SwiftUI#74]
If a product is purchased and a price is filled in, the number is used as price per single unit, even if multiple units are bought.

Example: 10 eggs are added with a price of €3,50. If entered like this, Grocy sets it to €3,50 per egg instead of €0,35 per egg. Same issue with all other quantities and products.

Would it be possible to have the ability to specify that the entered price is for the total amount of goods? Or have a way to set this as the default behavior?

**Comment by supergeorg** [comment]
Well, there is a Unit Price / Total Price toggle in the "normal" purchase view, not in the quick purchase.
But this toggle is nothing more than a fancy gadget, since it doesn't have any functionality 🙈

It should be fixed now (6411a53) and work the same way in the quick purchase screen (f9212ec).
