### ISSUE TITLE
"Doesn't Spoil" in Camera purchasing 

### ISSUE THREAD

**Issue by Tuphal** [supergeorg/Grocy-SwiftUI#95]
It would be a huge improvement, when during barcode scanning I can also select "doens't spoil" as when manually put on a entry. For example for sugar or toilet paper

"Nie überfällig" on manually shopping through the entry list:
![IMG_9004](https://user-images.githubusercontent.com/42291781/153396659-31bbd2b1-892d-407b-a7cc-e25ca6d06f59.PNG)

Missing "Nie überfällig" when purchasing with camera:
![IMG_9005](https://user-images.githubusercontent.com/42291781/153396693-cc7c18f8-4d2c-43c4-b835-c2840c47deb6.PNG)

**Comment by supergeorg** [comment]
Ok, I have added this to the quick scan mode form. This feature should be on-par with the "normal" purchase view for now.
