### ISSUE TITLE
allow "-1" on due days for products which doesn't spoil

### ISSUE THREAD

**Issue by Tuphal** [supergeorg/Grocy-SwiftUI#96]
we can't use the - button to get a "-1" entry for products which doesn't spoil.
![grafik](https://user-images.githubusercontent.com/42291781/153404930-33be3165-d6e5-46a2-9ab7-4fa3b3aafd5a.png)

File: Shared/Views/MasterData/MDForms/MDProductFormView.swift

old:
`MyIntStepper(amount: $defaultDueDays, description: "str.md.product.defaultDueDays", helpText: "str.md.product.defaultDueDays.info", minAmount: 0, amountName: defaultDueDays == 1 ? "str.day" : "str.days", systemImage: MySymbols.date)`

new:
`MyIntStepper(amount: $defaultDueDays, description: "str.md.product.defaultDueDays", helpText: "str.md.product.defaultDueDays.info", minAmount: -1, amountName: defaultDueDays == 1 ? "str.day" : "str.days", systemImage: MySymbols.date)`

**Comment by supergeorg** [comment]
Ok, I changed the minimum to -1 and added the corresponding handling to this value (so it gets set to doesn't spoil, not to today - 1).
