### ISSUE TITLE
Location filter in stock overview

### ISSUE THREAD

**Issue by ArnstadFredrik** [supergeorg/Grocy-SwiftUI#97]
I can't get the stock overview  section of the app to show what is moved to my freezer. It only seems to display products with freezer as standard location, and not items moved from fridge into the freezer. The app knows the product is in the freezer, if i search it up, but filtering for "freezer" location does not. But this it not a problem in the Grocy web-UI, there I am able to filter out "freezer" in the "Stock Overview" tab.

## Web UI
The two items in red
<img width="1324" alt="Skjermbilde 2022-03-01 kl  10 08 57" src="https://user-images.githubusercontent.com/41859568/156140647-521d07b8-cbb5-4eb0-9a65-b2b7379a5aeb.png">

## Mobile screen
Missing the two items in red
![mobile](https://user-images.githubusercontent.com/41859568/156140628-e95a909b-f21a-42e1-840a-87e136298351.jpg)

**Comment by supergeorg** [comment]
I can reproduce this bug but see no easy fix.

I am not certain where the web ui gets the information about all locations with the product (I only see one location).
This could be implemented by fetching `/stock/products/{productId}/locations` for every product.

Please let me know if there is an easier way with the API to query these, since this solution seems not like what the web ui is doing.

**Comment by berrnd** [comment]
> I am not certain where the web ui gets the information about all locations with the product (I only see one location).
> This could be implemented by fetching `/stock/products/{productId}/locations` for every product.

It's basically just that. On /stockoverview, all locations, where the corresponding product currently has stock, are rendered into a hidden column ([here](https://github.com/grocy/grocy/blob/632a5422362379e72adccf6e2735c16956145717/views/stockoverview.blade.php#L358-L360)), filtering is done by simply searching in that column ([here](https://github.com/grocy/grocy/blob/632a5422362379e72adccf6e2735c16956145717/public/viewjs/stockoverview.js#L50)).

You can also get the "product -> location"-info for all products at once by using the [`GET /objects/stock_current_locations`](https://demo.grocy.info/api/objects/stock_current_locations) endpoint (which is exactly what the /stockoverview page is based on).

**Comment by supergeorg** [comment]
Thanks @berrnd for explaining.
This was easier than expected.

The app now fetches the stock locations for every stock element and filters via these.
